# Generated by Django 3.1.4 on 2020-12-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('number', models.DecimalField(decimal_places=0, max_digits=3)),
                ('hour', models.DateTimeField()),
            ],
        ),
    ]
